# Site settings
title: ATK Developer Blog
username: Americastestkitchen
description: "TODO: Write this."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

# analytics
analytics:
  provider: google
  google:
    tracking_id: 'UA-52337213-1'

gems: [jekyll-gist]
